All tests passed
czertyaka/prosoft-c-stack pull request #1
Opened 2022-11-23 17:24 UTC by MyxaWanyuha

2022-11-24 18:21 UTC, czertyaka commented
Подскажите, пожалуйста, как собирали. Если собирали не с помощью CMakeLists.txt проекта, прошу указать как собирали: в первую очередь интересуют флаги компиляции. Если собирали с помощью CMakeLists.txt, прошу указать компилятор и его версию.

На моей машине командой, сгенерированной `cmake`
```
$ /usr/bin/cc  -I/tmp/MyxaWanyuha/build/googletest-prefix/src/googletest/googletest/include -I/tmp/MyxaWanyuha/build/googletest-prefix/src/googletest/googlemock/include  -Wall -Wextra -Wformat -Wformat-security -Werror -o CMakeFiles/cstack.dir/cstack.c.o -c /tmp/MyxaWanyuha/src/cstack.c
```
где
```
$ ls -al /usr/bin/cc
lrwxrwxrwx. 1 root root 3 Sep 12 00:09 /usr/bin/cc -> gcc
```
и
```
$ gcc --version
gcc (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
получаю следующие ошибки компиляции:
```
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_new’:
/tmp/MyxaWanyuha/src/cstack.c:36:27: error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Werror=sign-compare]
   36 |         for (int i = 0; i < g_table.count; ++i)
      |                           ^
/tmp/MyxaWanyuha/src/cstack.c:47:5: error: ‘auto’ is not at beginning of declaration [-Werror=old-style-declaration]
   47 |     const auto array_size = (g_table.count + ADDED_STACK_ENTRIES) * sizeof(stack_entry_t);
      |     ^~~~~
/tmp/MyxaWanyuha/src/cstack.c:47:16: error: type defaults to ‘int’ in declaration of ‘array_size’ [-Werror=implicit-int]
   47 |     const auto array_size = (g_table.count + ADDED_STACK_ENTRIES) * sizeof(stack_entry_t);
      |                ^~~~~~~~~~
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_free’:
/tmp/MyxaWanyuha/src/cstack.c:97:27: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   97 |         node_t* current = end->prev;
      |                           ^~~
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_valid_handler’:
/tmp/MyxaWanyuha/src/cstack.c:112:33: error: comparison of integer expressions of different signedness: ‘hstack_t’ {aka ‘int’} and ‘unsigned int’ [-Werror=sign-compare]
  112 |     return hstack < 0 || hstack >= g_table.count || g_table.entries[hstack].bIsReserved == false;
      |                                 ^~
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_size’:
/tmp/MyxaWanyuha/src/cstack.c:133:13: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  133 |         end = end->prev;
      |             ^
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_pop’:
/tmp/MyxaWanyuha/src/cstack.c:169:35: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  169 |     g_table.entries[hstack].stack = data->prev;
      |                                   ^
/tmp/MyxaWanyuha/src/cstack.c:172:5: error: ‘auto’ is not at beginning of declaration [-Werror=old-style-declaration]
  172 |     const auto result = data->size;
      |     ^~~~~
/tmp/MyxaWanyuha/src/cstack.c:172:16: error: type defaults to ‘int’ in declaration of ‘result’ [-Werror=implicit-int]
  172 |     const auto result = data->size;
      |                ^~~~~~
cc1: all warnings being treated as errors
```
В моем CMakeLists.txt задаются достаточно строгие флаги компиляции `-Wall -Wextra -Wformat -Wformat-security -Werror`. Вижу что ваш код может собирается с предупреждениями, если эти флаги убрать.

```
usr/bin/cc  -I/tmp/MyxaWanyuha/build/googletest-prefix/src/googletest/googletest/include -I/tmp/MyxaWanyuha/build/googletest-prefix/src/googletest/googlemock/include  -o CMakeFiles/cstack.dir/cstack.c.o -c /tmp/MyxaWanyuha/src/cstack.c
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_new’:
/tmp/MyxaWanyuha/src/cstack.c:47:16: warning: type defaults to ‘int’ in declaration of ‘array_size’ [-Wimplicit-int]
   47 |     const auto array_size = (g_table.count + ADDED_STACK_ENTRIES) * sizeof(stack_entry_t);
      |                ^~~~~~~~~~
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_free’:
/tmp/MyxaWanyuha/src/cstack.c:97:27: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   97 |         node_t* current = end->prev;
      |                           ^~~
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_size’:
/tmp/MyxaWanyuha/src/cstack.c:133:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  133 |         end = end->prev;
      |             ^
/tmp/MyxaWanyuha/src/cstack.c: In function ‘stack_pop’:
/tmp/MyxaWanyuha/src/cstack.c:169:35: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  169 |     g_table.entries[hstack].stack = data->prev;
      |                                   ^
/tmp/MyxaWanyuha/src/cstack.c:172:16: warning: type defaults to ‘int’ in declaration of ‘result’ [-Wimplicit-int]
  172 |     const auto result = data->size;
      |
```
Не могу точно знать, были ли у вас эти же предупреждения на вашем компиляторе. Предлагаю:

1. Исправить эти предупреждения. К сожалению, на больших проектах (особенно с легаси) без ворнингов редко обходится и все смирились с этим печальным фактом. Однако на нашем проекте, который измеряется десятками и сотнями строк, странно их иметь. Если на вашем компиляторе  их не было - можете не исправлять, кросс-версионности я не требую, но хорошо, конечно, когда она есть.
2. Исправить ошибки компиляции. В ТЗ нет указаний, на каком компиляторе и с какими флагами должен собираться проект, поэтому этот пункт не требование. Я приму у вас задачу, если ваш код будет собираться хоть как-то. Но одобрять запрос и мержить я буду только тот код, который будет собираться в рамках проекта, иначе я в своем проекте получу несобирающийся код)

2022-11-24 19:26 UTC, czertyaka requested changes

2022-11-24 19:26 UTC, czertyaka commented on cstack.c
> +#define SIZE_OF_NODE (sizeof(void*) + sizeof(unsigned int))
Как-то рискованно надеяться, что выравнивание структуры не поломает нам такую простую логику подсчета размера заголовка. Да, в этой конкретной структуре выравнивание позволяет так считать, но не советую так делать всегда.
Возможно, самым правильным решением будет и вовсе отказаться от поля `data` (напоминаю, что содержимое этого файла с заглушками было лишь рекомендацией с моей стороны), и считать размер аллоцируемого блока памяти так: `sizeof(node_t) + size`.

2022-11-24 19:26 UTC, czertyaka commented on cstack.c
> +                return i;
Забыли уменьшить счетчик `free_count`

2022-11-24 19:26 UTC, czertyaka commented on cstack.c
> +        return;
Раз уж вы начали прибегать к диагностике (`"Invalid stack handler!"`), стоит добавить ее и сюда.

2022-11-24 19:26 UTC, czertyaka commented on cstack.c
> +    node_t* data = g_table.entries[hstack].stack;
Советую использовать квалификатор `const` всегда, когда вы не собираетесь менять данные. Для функции `free` обычно используют приведение к неконстантному указателю. Не замечание, а совет)

2022-11-25 08:07 UTC, MyxaWanyuha commented
Из-за чего были проблемы: проект для VS2022 при помощи Cmake собирается, но не компилируется, поэтому я создал отдельный проект с тестами и добавил туда ссылки на файлы. Так как у вас не компилировалось я скачал WSL и скомпилировал при помощи GCC. Писал в make флаг DEBUG=0, но assert'ы все равно срабатывали и не давали  пройти тестам, поэтому я их убрал.

2022-11-26 11:34 UTC, czertyaka commented
> Из-за чего были проблемы: проект для VS2022 при помощи Cmake собирается, но не компилируется, поэтому я создал отдельный проект с тестами и добавил туда ссылки на файлы. Так как у вас не компилировалось я скачал WSL и скомпилировал при помощи GCC. Писал в make флаг DEBUG=0, но assert'ы все равно срабатывали и не давали пройти тестам, поэтому я их убрал.

Я починю `CMakeLists.txt` для msvc, последний, похоже, не поддерживает `/Wextra` (и может еще какие флаги). Потом можно будет смержить изменения `CMakeLists.txt` в ваш проект.

2022-11-26 11:47 UTC, czertyaka submitted a review, later dismissed
Задание считаю выполненным, мержить буду сам: хочу сделать папки для каждого студента и поправить в соответствие с этим CMakeLists.txt.

2022-11-26 11:47 UTC, czertyaka commented on cstack.c
> +#define CHECK_AFTER_ALLOC(ptr, return_value) if(ptr == NULL) \
Так не очень хорошо делать)
https://www.cs.technion.ac.il/users/yechiel/c++-faq/macros-with-if.html

2022-11-28 10:29 UTC, czertyaka approved these changes

2022-11-28 10:53 UTC, merged