Sokolov Vitaly
czertyaka/prosoft-c-stack pull request #10
Opened 2022-12-04 15:28 UTC by Sokolovych

Библиотека написана, сборка прошла наконец-то успешно, тесты (по крайней мере, на моем компе) пройдены на 100% (если что, файл с пошаговыми тестами с помощью printf до сих пор хранится))
В хэдер-файле добавил в строку create_new() void в скобки, чтобы ide не ругалась
В файле CMakeLists.txt пришлось убрать из 44 строки флаг /WX, ибо с ним VS отказывалась производить сборку проекта, ссылаясь на строку объявления массива нулевой длины char data[0] при объявлении структуры node

2022-12-08 19:03 UTC, czertyaka commented
> В хэдер-файле добавил в строку create_new() void в скобки, чтобы ide не ругалась

Правильно сделали, в вашем пулл-реквесте добавлю это в свой заголовочный файл

> В файле CMakeLists.txt пришлось убрать из 44 строки флаг /WX, ибо с ним VS отказывалась производить сборку проекта, ссылаясь на строку объявления массива нулевой длины char data[0] при объявлении структуры node

MSVC оказался строже чем gcc и clang. Ладно, согласен убрать этот флаг, хоть и не очень хочется)

2022-12-08 19:40 UTC, czertyaka requested changes
Опишите, пожалуйста, ваш подход к хранению стеков в таблице, в частности прошу объяснить значение `handlers_max`. Я, признаться, не уверен, что понял. Вы храните все обслуживаемые стек в начале таблицы без "пробелов"?

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +typedef int hstack_t;
Псевдоним уже объявлен в заголовочном файле)

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +        if (!g_table.entries[i].reserved)
Не факт что аллоцированная ранее память заполнена нулями, там может быть мусорное значение
https://en.cppreference.com/w/c/memory/malloc
> Allocates size bytes of **uninitialized** storage.

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +static unsigned int handlers_max; //УДАЛИТЬ ЕСЛИ НЕ ПОЛУЧИТСЯ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Не очень понял, зачем нужна эта переменная, вроде как `gtable.size` + поля `reserved` предоставляют необходимую информацию о том, сколько стеков из выделенных сейчас в использовании

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +    if (g_table.size == 0u)
Может лучше это в конец функции? У вас в теле `stack_free` уменьшается `g_table.size`.

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +    while (g_table.entries[hstack].top != NULL)
Будет гораздо читабельнее, если завести переменную для `g_table.entries[hstack].top`

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +                if (count == g_table.size)
`gcc` матерится:
error: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’

Переменной `count` согласно ее смыслу лучше быть типа `unsigned int`, иначе получается, что счетчик может быть отрицательным.

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +                    return;
Забыли освободить `stack_entries` - утчека памяти

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +            for (int i = 0; i <= handler; ++i)
Вы тут точно фигурные скобки не забыли?) Мои тесты похоже не покрывают эту часть, иначе бы выяснилось

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +        new_top->data[i] = src[i];
Так тоже можно, но есть `memcpy`)

2022-12-08 19:40 UTC, czertyaka commented on cstack.c
> +    char *src = (char *)data_in;
Если уж приводить, то хотя бы к константному указателю.

2022-12-09 17:58 UTC, Sokolovych commented on cstack.c
> +typedef int hstack_t;
Последствия экспериментов в онлайн-компиляторе без доступа к хэдер-файлу %)
Забыл в первый раз удалить, исправлено

2022-12-09 17:59 UTC, Sokolovych commented on cstack.c
> +        if (!g_table.entries[i].reserved)
Исправил на более подходящий calloc

2022-12-09 18:03 UTC, Sokolovych commented on cstack.c
> +    if (g_table.size == 0u)
Это да, поправил

2022-12-09 18:05 UTC, Sokolovych commented on cstack.c
> +    while (g_table.entries[hstack].top != NULL)
Оставлял все длинные конструкции поначалу, ибо это буквально первое практическое знакомство со структурами и указателями - чтобы не запутаться самому и понимать, что откуда идет. Попарвлено)

2022-12-09 18:07 UTC, Sokolovych commented on cstack.c
> +                if (count == g_table.size)
Это тоже верно: во всех циклах, где уместно (и где постарался не забыть) добавил по квалификатору 'unsigned'

2022-12-09 18:14 UTC, Sokolovych commented on cstack.c
> +                    return;
Если я правильно понял, про что речь, то в моем случае часть выделенной malloc'ом памяти освободить не удастся (https://stackoverflow.com/questions/2946660/in-c-is-it-possible-do-free-only-an-array-first-or-last-position)
Как понял, ситуация лечится realloc'ом ранее выделенного куска памяти
Соответственно, под временное хранение актуальных данных из g_table.entries был введен указатель rewrite_entries, g_table была реаллоцирована, после чего освободил rewrite_entries и приравнял к NULL

2022-12-09 18:15 UTC, Sokolovych commented on cstack.c
> +            for (int i = 0; i <= handler; ++i)
Оу, здесь просто код съехал, недоглядел. Исправлено)

2022-12-09 18:18 UTC, Sokolovych commented on cstack.c
> +        new_top->data[i] = src[i];
Про memcpy себе ранее записал, да, но все же захотелось разобраться и поэкспериментировать, как именно оно работает "изнутри" (ибо опять-таки, с указателями на указатели до этого момента не имел дела))

2022-12-09 18:23 UTC, Sokolovych commented on cstack.c
> +    char *src = (char *)data_in;
Вроде исправил на const char *src = (char *)data_in;, но буквально сейчас задумался, что мог понять неверно, и надо было const добавить в скобки - к тому, во что приводим

2022-12-11 09:31 UTC, Sokolovych commented
> Опишите, пожалуйста, ваш подход к хранению стеков в таблице, в частности прошу объяснить значение `handlers_max`. Я, признаться, не уверен, что понял. Вы храните все обслуживаемые стек в начале таблицы без "пробелов"?

В комментариях к коду описал примерную логику, которой придерживался. По итогу - handler_max нужен для отслеживания, сколько у нас стеков в принципе было создано (как используемых в данный момент, так и неиспользуемых), переменная count из stack_free отслеживает, на каком стеке из максимального количества у нас заканчивается число зарезервированных (например, на шестом из десяти возможных - при этом среди первых шести так же могут быть "пробелы"). Все для того, чтобы при вызове stack_free оптимизировать память под таблицу, чтобы у нее в конце не оставалось потенциальной кучи нулевых элементов

2022-12-21 19:47 UTC, czertyaka commented on cstack.c
> +    char *src = (char *)data_in;
Во время приведения (так называемого C-каста) указателей, можно приводить к типу указателя на константный тип, как вы:
```c
void* p;
const int* a = (const int*)p;
```
Однако это избыточно. Выражение `(const int*)p` является rvalue (https://en.cppreference.com/w/c/language/value_category). Если по простому, то стандарт ничего не говорит о размещении результата этого выражения в памяти, а значит, и использовать и изменить его программисту никак не получится. Поэтому здесь в `const`-квалификаторе нет особого смысла.
Переменная `a` в сниппете выше, с другой стороны, является lvalue. Программист знает, где в памяти размещена эта переменная, у нее есть время жизни, контролируемая программистом и т.д. Для нее вполне естественно использовать квалификаторы доступа.
Так что, для правильного приведения достаточно будет оставить `const` только у `a`.
```c
void* p;
const int* a = (int*)p;
```

2022-12-21 19:57 UTC, czertyaka commented on cstack.c
> +                    return;
Я здесь следующее имел ввиду:
1. вызвали `calloc` и аллоцировали память, сохранили в переменную `rewrite_entries`;
2. проверили `rewrite_entries` -- все ок, идем дальше;
3. вызвали `realloc`, не удалось аллоцировать память, сохранили `NULL` в `g_table.entries`;
4. проверили `g_table.entries`, выходим из функции, теряем указатель на выделенную память, сохраненный в `rewrite_entries` и, соответственно, возможность её освободить.

2022-12-21 19:58 UTC, czertyaka approved these changes

2022-12-21 19:59 UTC, czertyaka commented on cstack.c
> +static unsigned int handlers_max; //УДАЛИТЬ ЕСЛИ НЕ ПОЛУЧИТСЯ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Спасибо за развернутый ответ

2022-12-23 13:55 UTC, Sokolovych commented on cstack.c
> +                    return;
А ой, теперь да, увидел, поправил)

2023-11-19 19:52 UTC, closed without merging