Tests failed
czertyaka/prosoft-c-stack pull request #11
Opened 2022-12-04 19:07 UTC by AlreadyDone00

Здравствуйте. Все собирается и компилируется, но не проходят тесты. Фейлит на самом первом с сообщением: child aborted***exception. WSL, gcc version 9.4.0, cmake 3.16.3. Так же  тестировал в ручную в vs2020 и msvc.

2022-12-08 05:04 UTC, AlreadyDone00 commented
Во втором коммите тест прошёл

2022-12-10 18:59 UTC, czertyaka requested changes
В целом ок, самое серьезное замечение - по утечке памяти, остальные по мелочи, но их много

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +#include <assert.h>
Не вижу использования

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    g_table.entries = (stack_entry_t*)realloc(g_table.entries, (g_table.size+1) * sizeof(stack_entry_t));
Переаллокация таблицы на каждый запрос нового стека - дорогое и неоптимальное решение. В таблице могут быть уже освобожденные вхождения. А в такой реализации в поле `reserved` нет большого смысла.

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +     for (; top != NULL;)
Почему не `while`?

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +         g_table.entries[hstack].top = NULL;
Зачем это делать в цикле?

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    g_table.size--;
Подскажите, пожалуйста, какой смысл вы вложили в поле `size` таблицы?

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +	if ( hstack >= (int)g_table.size || g_table.entries == NULL|| hstack < 0)
Все-таки отступов лучше придерживаться

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    int handler = hstack;
Зачем нужна эта локальная переменная?

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +	if ( hstack >= (int)g_table.size || g_table.entries == NULL|| hstack < 0)
Если в будущем псевдоним `t_hstack` будет означать, к примеру, `long int`, то такое приведение
```c
(int)g_table.size
```
перестанет быть корректным. Либо приводите `size` к `t_hstack`, либо оба значения к одному типу.

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    else return 1;
Проверку `reserved` можно было бы добавить в `if` после всех остальных проверок

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    int i = 0;
Обычно именем `i` называют счетчики циклов, которые используются как индексы массивов (для обращения к элементу массива). Имя `size` здесь смотрелось бы куда лучше.

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +	node_t* node_cur_top = (node_t*)malloc(sizeof(node_t) + sizeof(node_prev_top->data));
Отступы конкретно пляшут)

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +		return;
Не освободили память, выделенную для `node_cur_top` -- утечка памяти

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    else if (g_table.entries[hstack].top != NULL)
Достаточно просто `else`

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    memmove(node_cur_top->data, data_in, size);
Почему не `memcpy`? Если у вас только что выделенная в куче память пересекается с памятью, предоставленной пользователем (совершенно нереалистичная ситуация), то пусть лучше UB начнет происходить здесь. Незачем предохраняться от такой ситуации.

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +	node_t* node_cur_top = (node_t*)malloc(sizeof(node_t) + sizeof(node_prev_top->data));
Размер указателя `node_prev_top->data` уже входит в размер структуры `node`, зачем дублировать?

2022-12-10 18:59 UTC, czertyaka commented on cstack.c
> +    node_cur_top->size = sizeof(node_cur_top->size) + sizeof(node_cur_top->prev) + size;
У вас фрейм стека (`node_t`) и данные фрейма находятся в разных участках памяти. Не понимаю, зачем может понадобиться суммарный размер.
Также, при таком расчете размера не учитывается [выравнивание структур](https://en.cppreference.com/w/c/language/object) (alignment).

2022-12-17 10:22 UTC, AlreadyDone00 commented on cstack.c
> +		return;
Честно говоря, тут я не понимаю. Если я освобожу память, выделенную для фрейма стека `node_cur_top`, разве я не потеряю указатели  `struct node* prev` и `void* data`? Да и в функции `stack_pop` я ведь освобождаю память при изъятии данных из стека. Чет я запутался.

2022-12-17 10:30 UTC, AlreadyDone00 commented on cstack.c
> +#include <assert.h>
Забыл удалить с предыдущего коммита. Исправил

2022-12-17 10:32 UTC, AlreadyDone00 commented on cstack.c
> +     for (; top != NULL;)
Как-то так вышло, что for использую чаще чем while. Не задумался и по привычке записал. Исправил.

2022-12-17 10:32 UTC, AlreadyDone00 commented on cstack.c
> +         g_table.entries[hstack].top = NULL;
Исправил.

2022-12-17 10:38 UTC, AlreadyDone00 commented on cstack.c
> +    g_table.size--;
Size это количество указателей на верхушки стека в массиве. Почему то думал, что раз уж очищаем стэк, то и size уменьшить нужно)))) Не принял во внимание, что размер массива не меняется. Исправил

2022-12-17 10:38 UTC, AlreadyDone00 commented on cstack.c
> +    g_table.entries = (stack_entry_t*)realloc(g_table.entries, (g_table.size+1) * sizeof(stack_entry_t));
Логично. Переделал

2022-12-17 10:38 UTC, AlreadyDone00 commented on cstack.c
> +    else if (g_table.entries[hstack].top != NULL)
Исправил

2022-12-17 10:40 UTC, AlreadyDone00 commented on cstack.c
> +    else return 1;
Исправил

2022-12-17 10:40 UTC, AlreadyDone00 commented on cstack.c
> +	if ( hstack >= (int)g_table.size || g_table.entries == NULL|| hstack < 0)
Привел оба к одному значению

2022-12-17 10:40 UTC, AlreadyDone00 commented on cstack.c
> +    int handler = hstack;
Исправил

2022-12-17 10:42 UTC, AlreadyDone00 commented on cstack.c
> +	if ( hstack >= (int)g_table.size || g_table.entries == NULL|| hstack < 0)
Открыл у себя и таких проблем не заметил. Возможно из-за того, что отступы у меня были с помощью таба. Вроде исправил

2022-12-17 10:42 UTC, AlreadyDone00 commented on cstack.c
> +    int i = 0;
Исправил

2022-12-17 10:42 UTC, AlreadyDone00 commented
Все замечания устранил, кроме утечки памяти.

2022-12-21 20:13 UTC, czertyaka commented on cstack.c
> +		g_table.size++;
А если `g_table.entries` = `NULL`?

2022-12-21 20:13 UTC, czertyaka commented on cstack.c
> +	if ( hstack >= (int)g_table.size || g_table.entries == NULL|| hstack < 0)
Вы можете смотреть прямо в гитхабе) А вообще, распространенная проблема с отступами, разные редакторы их по разному понимают. Но почти все имеют возможность их настроить.

2022-12-21 20:13 UTC, czertyaka commented on cstack.c
> +	if ( hstack >= (int)g_table.size || g_table.entries == NULL|| hstack < 0)
Лучше бы привели к `t_hstack`, ну да ладно, тут не критично)

2022-12-21 20:13 UTC, czertyaka commented on cstack.c
> +		return;
На этом этапе (проверка `node_cur_top->data`) вы в таблицу еще ничего не успели положить, вся выделенная память хранится в локальных переменных. И как только вы выйдете из функции, значения указателей в этих переменных пререстанут вам быть доступными. Когда вы выйдете из функции на этом `return`, вы окажетесь в ситуации, что в куче память есть, а указателя у вас на нее нет.
Вот такой сценарий:
1. `node_t* node_cur_top = (node_t*)malloc(sizeof(node_t));` -- успешно;
2. `node_cur_top->data = (void*)malloc(size);` -- неуспешно;
3. проверяем `node_cur_top->data`, выходим из функции, память из п.1 не освободилась.

2022-12-21 20:13 UTC, czertyaka requested changes
Ваша работа принята, все дальнейшие ревью и обсуждения -- по вашему желанию)

2022-12-21 20:15 UTC, czertyaka commented on cstack.c
> +		return;
На этом этапе (проверка `node_cur_top->data)` вы в таблицу еще ничего не успели положить, вся выделенная память хранится в локальных переменных. И как только вы выйдете из функции, значения указателей в этих переменных пререстанут вам быть доступными. Когда вы выйдете из функции на этом `return`, вы окажетесь в ситуации, что в куче память есть, а указателя у вас на нее нет.
Вот такой сценарий:
1. `node_t* node_cur_top = (node_t*)malloc(sizeof(node_t));` -- успешно;
2. `node_cur_top->data = (void*)malloc(size);` -- неуспешно;
3. проверяем `node_cur_top->data`, выходим из функции, память из п.1 не освободилась.

2023-11-19 19:52 UTC, closed without merging