Домашнее задание 1
czertyaka/prosoft-c-stack pull request #17
Opened 2022-12-11 17:50 UTC by 1user-name1

2022-12-11 17:52 UTC, 1user-name1 commented
ДЗ сдал

2022-12-22 18:29 UTC, czertyaka requested changes
Несмотря на то, что дз оценивается по состоянию на момент дедлайна и никакие последующие ревью, обсуждения и исправления на оценку не влияют, я по возможности стараюсь делать ревью. Дальнейшее обсуждение и исправления по вашему желанию и возможности)

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +struct stack_t{
Не замечание, а вопрос: по каким правилас названы структуры?) Суффикс `_t` здесь обозначает таблицу?

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +	copy_data_pointer = (void*) malloc(size); // Выделяем память для копирования данных
Не хватает проверки возвращаемого значения `malloc` (в остальных местах тоже)

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +struct node *node;
Глобальные переменные лучше всегда инициализировать

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +    stack_table->stack_list[hstack].stack_exists = 1; // Флаг "несуществования" стека
`enum` смотрелся бы лучше [магических чисел](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +	stack_table->stack_list[stack_table->table_size].top_of_stack = NULL;
Локальные переменные
```c
struct stack * last_stack = stack_table->stack_list;
const unsigned int size = stack_table->table_size;
```
сделали бы код читабельнее.

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +    return stack_table->stack_list[hstack].stack_exists;
А если передам `-1`? `-100`? `100500`?

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +	if(data_in == NULL)
Должна быть и проверка `hstack`, желательно через `stack_valid_handler` (как и во всех других функциях, принимающих дескриптор).

2022-12-22 18:29 UTC, czertyaka commented on cstack.c
> +		printf("Error: null pointer");
Диагностика -- это хорошо, но почему продолжаем выполнять функцию?)

2023-11-19 19:52 UTC, closed without merging