Pull request 0.1
czertyaka/prosoft-c-stack pull request #4
Opened 2022-11-29 20:12 UTC by ilya-talankin

Здравствуйте! Написал вот такую библиотеку. Проверял вручную, вроде работает, но смотрится очень сложно (особенно строки типа handlers_table[hstack] -> p_top_node -> node_number = new_node_number). Как можно сделать код более простым? И правильно ли в целом построена архитектура? Ещё очень интересует оптимальность использования памяти, т. к. очень сложно проверить вручную, а  собрать с помощью cmake у меня не получилось (на windows что-то с самим cmake, а на подсистеме WSL вылезает ошибка с гугл тестами, в ближайшее время напишу о ней на почту)

2022-11-29 20:39 UTC, ilya-talankin commented
Из-за старой fork показывается, что я изменил 5 файлов. Это можно как-то исправить?

2022-11-30 04:44 UTC, czertyaka commented
> Из-за старой fork показывается, что я изменил 5 файлов. Это можно как-то исправить?

Вижу только один измененный файл, уже поправили?

2022-11-30 05:04 UTC, czertyaka commented
При самостоятельной сборке рекомендую взять флаги компилятора из CMakeLists.txt.

- `gcc`, `clang`: `-Wall -Wextra -Wformat -Wformat-security -Werror`
- `msvc`: `/Wall /WX`

Сейчас ваш код не собирается с этими флагами.
[build.log](https://github.com/czertyaka/prosoft-c-stack/files/10119627/build.log)

2022-11-30 05:45 UTC, czertyaka requested changes
По поводу правильности обращения к памяти - написал, на что обратил внимание невооруженным глазом. Когда ваше решение будет собираться с флагами, прогоню тесты, может еще что всплывет.

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +stack_t** handlers_table;
Почему двойной указатель? В `stack_new` спользуете вы его как обычный указатель.
```
+------------------------+     +------------------------+
|                        |     |                        |
|   +----------------+   |     |   +----------------+   |
|   | handlers_table |------------>| 0x1FA75...     |   |
|   +----------------+   |     |   +----------------+   |
|   = 0x1FA75...         |     |                        |
+------------------------+     +------------------------+
.data                          heap
```

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +    handlers_table[handler] = malloc(sizeof(stack_t*));
Ошибка в размере аллоцируемой памяти.
https://godbolt.org/z/nabdfczTa

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +    while (handlers_table[hstack] -> p_top_node != NULL) {
Насчет читаемости. Если вам не нравятся цепочки обращений к полям структуры `handlers_table[hstack] -> p_top_node -> data`, то здесь это решается просто:

```c++
const node_t* top = handlers_table[hstack]->p_top_node;
while (top != NULL)
{
    const node_t* prev = top->prev;
    free(top->data);
    free(top);
    top = prev;
}
```

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +        //Правильно ли освобождаю память?
Правильно

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +    if ((hstack >= 0) && (hstack < table_size) && (handlers_table[hstack] -> reserved == 1)){
Тут можно обойтись без условного оператора)
Если хотите оставить,  то подкорректируйте по стилю: у вас тело положительного условия в `{}`, а отрицательного - без.

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +        if (handlers_table[hstack] -> p_top_node != NULL){
Здесь по читаемости тот же совет: вы дважды обращаетесь к полю структуры. Ради этого можно и завести переменную
```c
const node_t* top = handlers_table[hstack]->p_top_node;
```
Из-за оверхеда не волнуйтесь -- компилятор, вероятнее всего, соптимизирует эту переменную и реально она на стеке создаваться не будет.

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +    if ((stack_valid_handler(hstack) == 0)&&(data_in != NULL)){
Если переданный размер равен нулю, то можно прервать выполнение функции уже здесь.

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +        struct node* p_prev = handlers_table[hstack] -> p_top_node; //saving pointer to prev element
Вы же ввели псевдоним `node_t`, можно уже не писать `struct node`.

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +        handlers_table[hstack] -> p_top_node -> data = (char*) malloc (size);
В принципе, решение в котором вы на один `push` делаете две аллокации, принимается, но можно обойтись и одной. Это оптимальнее как с точки зрения быстродейтсвия, так и с точки зрения эффективности использования памяти (уменьшается фрагментация).

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +        int size_to_copy = (handlers_table[hstack] -> p_top_node -> size > size) ? size : handlers_table[hstack] -> p_top_node -> size;
Проверка не учитывает ситуацию, когда нам передали `size = 0`

2022-11-30 05:45 UTC, czertyaka commented on cstack.c
> +        //Правильно ли освобождаю память?
Правильно

2022-11-30 07:03 UTC, ilya-talankin commented
> > Из-за старой fork показывается, что я изменил 5 файлов. Это можно как-то исправить?
> 
> Вижу только один измененный файл, уже поправили?

Да, поправил

2022-11-30 07:21 UTC, czertyaka commented on cstack.c
> +stack_t** handlers_table;
Понял, что вы делаете)
Расскажите, почему решили хранить в таблице указатели `stack_t*`, не проще ли хранить `stack_t`?

2022-12-02 07:57 UTC, czertyaka requested changes

2022-12-02 07:57 UTC, czertyaka commented on cstack.c
> +    node_t* top = handlers_table[hstack].p_top_node;
Данные не меняете, можно и `const`. Для `free` можно воспользоваться приведением.

2022-12-02 07:57 UTC, czertyaka commented on cstack.c
> +    struct node* prev;
А зачем убрали `const`? При правильном подходе к работе с узлами списка вам не придется их менять. Только создавать/удалять.

2022-12-02 07:57 UTC, czertyaka commented on cstack.c
>      char* data;
Данные, на которые указывает это поле, тоже можно сделать константными

2022-12-02 07:57 UTC, czertyaka commented on cstack.c
> +        handlers_table = realloc(handlers_table, (table_size - size_to_reduce) * sizeof(stack_t));
Тут два вопроса:
1. Зачем? Пусть будет незарезервированное вхождение в таблицу. Оно потом зарезервируется, когда вызовется `stack_new`. Конечно, когда таблица полностью пустая, ее нужно освободить. Можете оставить так, но как по мне это неоптимально.
2. Представьте следующую ситуацию (псевдокод):
    ```
    +------+------+------+------+
    |stack1|stack2|stack3|stack4|
    +------+------+------+------+
    stack_free(2)
    +------+------+------+------+
    |stack1|NIL   |stack3|stack4|
    +------+------+------+------+
    realloc(3)
    +------+------+------+
    |stack1|NIL   |stack3|
    +------+------+------+
    ```  
    Если я правильно понял вашу реализацию, то потерялся один четвертый стек.

2022-12-02 07:57 UTC, czertyaka commented on cstack.c
> +        node_t* p_prev = top; //saving pointer to prev element
Может проще сразу
```c
node_t* p_prev = handlers_table[hstack].p_top_node;
```
Я не вижу чтобы дальше это значение `top` использовалось

2022-12-02 07:57 UTC, czertyaka commented on cstack.c
> +int main()
Уберите) Это библиотека, а не исполняемый файл, тут не должно быть entry point
Если хочется самостоятельного тестирования, напишите main.c, соберите main.o, слинкуйте с libstack.a и получите исполняемый файл
Но в систему контроля версий это не надо добавлять

2022-12-02 08:03 UTC, czertyaka commented
У вас неплохое решение хранить номер узла списка прямо в списке. Обеспечивает константное время доступа при вызове `stack_size`.

2022-12-02 10:44 UTC, ilya-talankin commented
Блин, я не думал, что мои коммиты будут Вам видны... Мне казалось, что они только пол реквеста вам отобразяться. Не обращайте внимания, это мои черновые версии. Можно как-то сделать, чтобы они не шли в пул реквест? Или все черновики отдельной веткой делать?

2022-12-02 11:44 UTC, ilya-talankin commented on cstack.c
> +        handlers_table = realloc(handlers_table, (table_size - size_to_reduce) * sizeof(stack_t));
У меня была такая идея: итератор идёт с конца массива и считает, сколько мест с конца свободны и уменьшает массив на это количество. В цикле for есть проверка handlers_table[i].reserved == 0, чтобы случайно не захватить действующие стеки

2022-12-02 11:52 UTC, ilya-talankin commented on cstack.c
> +        handlers_table = realloc(handlers_table, (table_size - size_to_reduce) * sizeof(stack_t));
аа, увидел, что || с && перепутал, исправлю. Вообще этот кусок призван оптимизировать размер таблицы. Если когда-то существовало 100 стеков, а потом все, кроме одного (к примеру пятого) не используются, то места для 95 стеков будут просто пустовать. А так мы уменьшим размер таблицы до 5. Конечно, в ситуации, где остался один 95-й стек, это не сильно поможет, так как можно сократить только 5 мест.
А вообще, стоит таким заниматься? Или это всё копейки и вместо оптимизации я получу только более долгую работу библиотеки за счёт перебора всего массива?

2022-12-02 19:41 UTC, ilya-talankin commented
Все гугл тесты прошли успешно, теперь можно проверять))

2022-12-02 20:09 UTC, ilya-talankin commented on cstack.c
> +    if ((stack_valid_handler(hstack) == 0)&&(handlers_table[hstack].p_top_node != NULL)) {
Я правильно понимаю, что условия в if проверяются по порядку? То есть программа сперва проверит валидность, а потом уже обратится к элементам стека с хендлером hstack?

2022-12-02 20:28 UTC, ilya-talankin commented on cstack.c
> +hstack_t stack_new(){
Подскажите, как лучше писать? 
foo(){
<body>
} 
или 
foo()
{
<body>
}

2022-12-02 20:30 UTC, ilya-talankin commented on cstack.c
> +        handlers_table = realloc(handlers_table, (table_size - size_to_reduce) * sizeof(stack_t));
Подскажите, как вы делаете такие красивые картинки из символов?))

2022-12-02 20:37 UTC, ilya-talankin commented on cstack.c
> +        *(unsigned int*)&new_top -> size = size;
Приведение типов на  stackoverflow подсмотрел, но если честно, синтаксис не до конца понял. Проверьте, пожалуйста, на правильность. Можно ли тут как-то без приведения обойтись?

2022-12-04 05:20 UTC, czertyaka commented on cstack.c
> +hstack_t stack_new(){
Тут на ваш вкус) Если интересно, то можно почитать про разные соглашения по  стилю кодирования С/C++ - ниже список coding-style, принятых в разных проектах и компаниях. У каждого есть свои преимущества и недостатки, но все они касаются скорее эстетической составляющей кодовой базы, чем практической. И даже тут последовательность и единообразие важнее, чем сам выбор coding-style.

1. [LLVM coding standards](https://llvm.org/docs/CodingStandards.html)
2. [Google’s C++ style guide](https://google.github.io/styleguide/cppguide.html)
3. [Chromium’s style guide](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/styleguide/styleguide.md)
4. ...

2022-12-04 05:22 UTC, czertyaka commented on cstack.c
> +    if ((stack_valid_handler(hstack) == 0)&&(handlers_table[hstack].p_top_node != NULL)) {
Если кратко -- да, если подробно:
https://en.cppreference.com/w/c/language/eval_order
> There is a sequence point after evaluation of the first (left) operand and before evaluation of the second (right) operand of the following binary operators: && (logical AND), || (logical OR), and , (comma).

2022-12-04 05:30 UTC, czertyaka commented on cstack.c
> +        handlers_table = realloc(handlers_table, (table_size - size_to_reduce) * sizeof(stack_t));
Нажав на кнопку `Add code` можно добавить моноширинный текст. Этого же можно добиться с помощью символа "`". А вообще можете почитать про [Markdown](https://docs.github.com/ru/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), он достаточно популярен сейчас
![image](https://user-images.githubusercontent.com/69390349/205476058-11181f9f-0089-4c0d-b7dd-d5b5f30ea1f8.png)

2022-12-04 05:37 UTC, czertyaka commented on cstack.c
> +        handlers_table = realloc(handlers_table, (table_size - size_to_reduce) * sizeof(stack_t));
> итератор идёт с конца массива 
Не обратил внимания, тогда вопросов не имею)

> А вообще, стоит таким заниматься? Или это всё копейки и вместо оптимизации я получу только более долгую работу библиотеки за счёт перебора всего массива?
Если вам важнее быстродействие, чем память - не стоит. Если наоборот - то стоит. У нас библиотека общего назначения, и в таких условиях наверное правильнее считать, что экономия памяти важнее перфоманса. Копейками как раз будет обход 95 элементов массива.

2022-12-04 05:59 UTC, czertyaka requested changes

2022-12-04 05:59 UTC, czertyaka commented on cstack.c
> +        *(unsigned int*)&new_top -> size = size;
```c
((struct node*)new_top) -> prev = p_prev;
```
А зачем вы тут приводите тип? Выше переменная `new_top` объявлена с типом `node_t`.
Порядок операций в следующих двух строках будет такой ([C Operator Precedence](https://en.cppreference.com/w/c/language/operator_precedence)):
```c
( * ( (unsigned int*) ( & ( new_top -> node_number ) ) ) )
//4                 3   2           1
```
Но непонятно, зачем делать сложно и нечитаемо, когда можно просто
```c
new_top->node_number = new_node_number;
```

2022-12-04 06:16 UTC, ilya-talankin commented on cstack.c
> +        *(unsigned int*)&new_top -> size = size;
Я это сделал, потому что мне new_top - указатель на константную структуры, поля которой компилятор не разрешает изменять. Поэтому я приводил new_top к указателю на неконстантную структуру (struct node*)

2022-12-04 06:19 UTC, ilya-talankin commented on cstack.c
> +        *(unsigned int*)&new_top -> size = size;
Строка new_top->node_number = new_node_number; не компилируется
error: assignment of member ‘node_number’ in read-only object

2022-12-04 06:33 UTC, ilya-talankin commented on cstack.c
> +        *(unsigned int*)&new_top -> size = size;
Могу так исправить:
((struct node*)new_top) -> prev = p_prev;
((struct node*)new_top) -> node_number = new_node_number;
((struct node*)new_top) -> size = size;
Так лучше читаемость будет?

2022-12-05 18:18 UTC, czertyaka approved these changes

2022-12-05 18:18 UTC, czertyaka commented on cstack.c
> +        *(unsigned int*)&new_top -> size = size;
Не сразу обратил внимание, что `t_node` - псевдоним типа `const struct node`, а не `struct node`. Теперь стало ясно, почему вы раньше писали `struct node` вместо `t_node`.
Писать `const` в `typedef` - нераспространенная практика. Если это необходимо, обычно делают так:
```c
typedef int alias;
typedef const alias const_alias;
```
Для улучшения читаемости можно объявить `new top` без `const` любым удобным вам способом - или убрать `const` из псевдонима, или объявить переменную с типом `struct node`.

2022-12-05 18:19 UTC, czertyaka commented
Закрывать pull-request буду самостоятельно.

2022-12-08 17:45 UTC, merged