Homework
czertyaka/prosoft-c-stack pull request #5
Opened 2022-11-30 18:03 UTC by Sladkoeshechka

Цымбаленко Дмитрий. Сдаю работу на проверку. Тесты все прошла.

2022-12-04 07:17 UTC, czertyaka reviewed
Существенных замечаний нет, но нужно обосновать, почему выбрали такой подход к аллокации новых элементов таблицы.

2022-12-04 07:17 UTC, czertyaka commented on cstack.c
> +        g_table.table = (stack_t*)realloc(g_table.table, g_table.reserved_size * sizeof(stack_t));
А если в начале таблицы уже есть незанятые вхождения (`size == freed_stack_size`)? Можно было бы использовать имеющуюся память вместо переаллокации.
Рассмотите такой код:
```c
while (true) {
    t_hstack hstack = stack_new();
    stack_free(hstack);
}
```
Код, очевидно, плохой, так как он представляет собой бесконечный цикл. Но в вашем случае он приведет не только к зависанию программы, но и к бесконечному увеличению потребления RAM.

Проверил профилировщиком. В test.cpp добавил
```c++
TEST(AllAPITest, InfiniteLoop)
{
    while (true)
    {
        hstack_t stack = stack_new();
        stack_free(stack);
        usleep(10);
    }
}
```
На изображении результат работы профилировщика `mprof`.
![Figure_1](https://user-images.githubusercontent.com/69390349/205478827-cde334ed-79ac-443e-ac07-8fac270cd37e.png)

2022-12-04 07:17 UTC, czertyaka commented on cstack.c
> +    }
Раз добавили диагностику `printf`-ами, не лишним будет дописать `else`.

2022-12-04 07:17 UTC, czertyaka commented on cstack.c
> +        node_t* temp_top = g_table.table[hstack].top;
Префиксы `temp_` наверное излишни, и так понятно, что у этих переменных время жизни ограничивается телом `if`.

2022-12-05 18:08 UTC, Sladkoeshechka commented
Здравствуйте. Исправил все замечания. Дополнительный тест с бесконечным циклом тоже проходится. Если честно, я не совсем понял. Я думал, что вы добавите его в origin в test.cpp. Но я сам добавил его в своем файле в моем локальном репозитории.

2022-12-05 18:09 UTC, Sladkoeshechka commented on cstack.c
> +        g_table.table = (stack_t*)malloc(g_table.reserved_size * sizeof(stack_t));
Мне так нравится больше)

2022-12-05 18:09 UTC, Sladkoeshechka commented on cstack.c
> +        g_table.table = (stack_t*)realloc(g_table.table, g_table.reserved_size * sizeof(stack_t));
Исправил

2022-12-05 19:40 UTC, czertyaka commented
> Если честно, я не совсем понял. Я думал, что вы добавите его в origin в test.cpp.

Нет, это было просто для примера, и мне было удобнее написать этот код в `test.cpp`, чем компилировать отдельный исполняемый файл. А вам я его привел для наглядности, чтобы было понятно, как использую вашу библиотеку и какой результат получаю. Профилирование же в юнит-тесты не входит.

2022-12-05 19:42 UTC, czertyaka requested changes
Уберите изменения из `test.cpp` и можно будет вливать. Тест все равно ничего не делает - в нем нет проверок.

2022-12-05 19:49 UTC, Sladkoeshechka commented
Здравствуйте еще раз. Все, test.cpp вернул в начальное состояние.

2022-12-08 18:22 UTC, merged