Дз по стеку
czertyaka/prosoft-c-stack pull request #6
Opened 2022-12-02 13:30 UTC by Onishenko-sci

Гугл тесты не хочет собирать + проводить. Проверялся только один .test и то его я не прошёл, но т.к. там не показывает что конкретно я не прошёл, проходить и не стал.
Тем не менее, сам написал некоторые тесты и их попроходил. Вроде работает.

2022-12-04 07:20 UTC, czertyaka commented
Взгляните во вкладку `Files changed`. Вы переместили файлы с исходным кодом в папку `src/` и добавили `.vscode/`. Нужно, чтобы из измененных файлов был только `cstack.c` и его расположение было тем же (корневая директория репозитория).

2022-12-04 07:21 UTC, czertyaka commented
Также обратите внимание, что `cstack.h` менять не нужно. В заголовочном файле определно API, ваша задача - его реализовать.

2022-12-04 11:21 UTC, Onishenko-sci commented
Всё поправил, но тесты всё равно не проходятся. 
![image](https://user-images.githubusercontent.com/118472680/205487586-b9b8d40c-7ecf-4473-82ca-b14ae2674722.png)

2022-12-05 19:47 UTC, czertyaka commented
> Всё поправил, но тесты всё равно не проходятся.

Выполните
```bash
$ ./test_.
```
и увидите подробный вывод теста. В вашем случае ругается адрес санитайзер - случилась ошибка сегментации в функции `stack_pop`. Ревью сделаю чуть позже, можете пока сами посмотреть, вдруг увидите что не так. Если не найдете, я во время ревью выясню.

2022-12-05 19:48 UTC, czertyaka commented on CMakeLists.txt
> +add_homework(.)
```suggestion
add_homework(default .)
```

2022-12-08 18:15 UTC, czertyaka requested changes

2022-12-08 18:15 UTC, czertyaka commented on cstack.c
> +    memcpy(data_out, stacks_head[stack_id].head_pointer->data, stacks_head[stack_id].head_pointer->size);
Чисто из эстетических соображений я бы предложил
```c
const node* top = stacks_head[stack_id].head_pointer;
const unsigned int writen_size = top->size;
memcpy(data_out, top->data, writen_size);
```

2022-12-08 18:15 UTC, czertyaka commented on cstack.c
> +    if (size < stacks_head[stack_id].head_pointer->size)
Тест падает потому что здесь неправильная очередность проверок. Разыменование указателя должно происходить после проверки размера стека.

2022-12-10 10:21 UTC, Onishenko-sci commented on cstack.c
> +typedef struct node_t node;
Как по мне, удобнее добавлять сразу к имени, чтобы потом постоянно не писать `_t`

2022-12-10 10:22 UTC, Onishenko-sci commented on cstack.c
> +enum
Видел, но если можно реализовать двумя строками, не лучше ли сделать так ?

2022-12-10 10:23 UTC, Onishenko-sci commented on cstack.c
> +    memcpy(data_out, stacks_head[stack_id].head_pointer->data, stacks_head[stack_id].head_pointer->size);
Действительно, я что-то не догадался

2022-12-10 10:49 UTC, Onishenko-sci commented on cstack.c
> +    if (size < stacks_head[stack_id].head_pointer->size)
Поменял местами. Тест всё равно не проходит

2022-12-21 19:14 UTC, czertyaka commented on cstack.c
> +    if (size < stacks_head[stack_id].head_pointer->size)
А что в выводе `test_default`? У меня проходит.

2022-12-21 19:16 UTC, czertyaka commented on cstack.c
> +enum
Если считаем количество строк, то
```c
#include <stdbool.h>
```
выигрывает) Но не настаиваю, раз так нравится

2022-12-21 19:18 UTC, czertyaka approved these changes

2022-12-21 19:20 UTC, czertyaka commented on cstack.c
> +    if (size < stacks_head[stack_id].head_pointer->size)
Обратил внимание
> Тем не менее, сам написал некоторые тесты и их попроходил. Вроде работает.

У вас свои тесты? Если да, то можете показать, что конкретно не работает, разберемся.

2022-12-22 19:50 UTC, Onishenko-sci commented on cstack.c
> +    if (size < stacks_head[stack_id].head_pointer->size)
Вот вывод test_default. Писал в codespaces, может из-за них что-то не работает. 
С тестами,которые написал сам, всё в порядке. 
![image](https://user-images.githubusercontent.com/118472680/209214433-1feebb14-2f46-4b86-ac8f-a68cb12832c4.png)

2023-11-19 19:52 UTC, closed without merging