Update cstack.c
czertyaka/prosoft-c-stack pull request #9
Opened 2022-12-03 12:38 UTC by ChugaevMV

2022-12-08 18:59 UTC, czertyaka requested changes
Тесты пока не проходят из-за указанных недочетов

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +#define OUT_OF_MEMORY   -102
Не увидел использования

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +       g_table.entries = (stack_entry_t*)malloc(sizeof(stack_entry_t));
Нет проверки на NULL. Ниже в цикле вы обращаетесь к элементам `entries`, при неудачной аллокации тут получим ошибку сегментации внизу.

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +    return;
Лучше не отступать от использования отступов)

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +    if (g_table.entries == NULL || hstack == -1 || hstack >= (int)g_table.size || g_table.entries[hstack].reserved == 0)
А если передам `-2` или `-10`? Поток выполнения дойдет до проверки условия `g_table.entries[hstack].reserved == 0` и получаем неопределенное поведение (UB)

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +        stack_size += 1;
Здесь можно использовать пост- или преинкремент)

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +    node_t* New_Top_Stack = (node_t*) malloc(sizeof(node_t) + sizeof(Top_Stack->size));
После каждой аллокации должна быть проверка ее результата, иначе рискуем разыменовать нулевой указатель

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +    if (stack_valid_handler(hstack) == 1 || data_out == NULL || size == 0 || g_table.entries[hstack].top_stack == NULL)
Не хватает проверки того, что размера переданного буфера достаточно для того, чтобы скоприровать в него данные с выерхушки стека

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +        if (g_table.entries[i].reserved == 0)
Не надо надеяться, что выделенная память будет заполнена нулями. Там может оказаться мусорное значение, нужно явно инициализировать память, хотя бы с помощью `memset`

> void *malloc( size_t size );
> Allocates size bytes of **uninitialized** storage.

https://en.cppreference.com/w/c/memory/malloc

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +    }
Нужно обновить поле размера таблицы

2022-12-08 18:59 UTC, czertyaka commented on cstack.c
> +        g_table.entries = (stack_entry_t*)realloc(g_table.entries, (sizeof(stack_entry_t)) * (g_table.size + 1));
После реаллокации нужно инициализировать всю новую память. В вашем случае это поля последней структуры `stack_entry_t`.

2022-12-11 16:05 UTC, ChugaevMV commented
Олег, файлы допилил, надеюсь вы увидели)

2022-12-21 19:30 UTC, czertyaka requested changes
Всё ревью, которое я делаю после дедлайна не влияет на оценку, это скорее для вас и для меня. Поэтому вся дальнейшая работа на ваше усмотрение)
В целом решение принято, но нужно вычистить комментарии

2022-12-21 19:30 UTC, czertyaka commented on cstack.c
> +                //g_table.entries[i].top_stack = NULL;
Закомментированные участки кода могут быть полезны во время рефакторинга, если не хочется/неудобно пользоваться `git diff`. Но включать их в коммиты -- уже перебор.

2023-11-19 19:52 UTC, closed without merging